efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300MiB
userSwapChoices:
    - none
    - small
    - suspend
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs"]
enableLuksAutomatedPartitioning: true
